ifdef CONFIG_MACH_MSM8974_G3_CN
obj-$(CONFIG_MACH_MSM8974_G3) += board-8974-g3.o board-8974-g3-cn-gpiomux.o
else
obj-$(CONFIG_MACH_MSM8974_G3) += board-8974-g3.o board-8974-g3-gpiomux.o
endif

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g3-rfkill.o
